apiVersion: v2
name: coretexdb
description: CoretexDB Enterprise Vector Database Helm Chart
type: application
version: 1.0.0
appVersion: "latest"
keywords:
  - coretexdb
  - vector-database
  - embedding
  - similarity-search
home: https://coretexdb.io
sources:
  - https://github.com/coretexdb/coretexdb
maintainers:
  - name: CoretexDB Team
    email: support@coretexdb.io
dependencies:
  - name: prometheus
    version: "25.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "6.60.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  - name: loki
    version: "6.0.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled
