apiVersion: v1
kind: Namespace
metadata:
  name: coretexdb
  labels:
    app.kubernetes.io/name: coretexdb
    app.kubernetes.io/instance: coretexdb
    app.kubernetes.io/version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    app.kubernetes.io/name: logging
